### ISSUE TITLE
Could not start tcell for gomatrix. View ~/.gomatrix-log for error messages.

### ISSUE THREAD

**Issue by bahamat** [gdamore/gomatrix#3]
```
2015/10/29 20:09:27 -------------
2015/10/29 20:09:27 Starting gomatrix. This logfile is for development/debug purposes.
2015/10/29 20:09:27 Cannot start gomatrix, screen.Init() gave an error:
invalid argument
```

**Comment by gdamore** [comment]
I've changed some things recently, so possibly I busted something.  Can you supply some details about your environment?  (I'm especially interested in your OS, $TERM, $LANG, $LC_ALL, and $LC_CTYPE settings.)

**Comment by bahamat** [comment]
```
$ printf 'uname -v: %s\n$TERM: %s\n$LANG: %s\n$LC_ALL: %s\n$LC_CTYPE\n' \
> $(uname -v) $TERM $LANG $LC_ALL $LC_CTYPE
uname -v: joyent_20151015T063543Z
$TERM: xterm-256color
$LANG: en_US.UTF-8
$LC_ALL: 
$LC_CTYPE
```

**Comment by gdamore** [comment]
Ah.  Are you using Go v1.5 or newer?  On illumos variants (including SmartOS) we need a version of Go that supports  cgo.

**Comment by bahamat** [comment]
Using base-64-lts image. Go is from pkgsrc 2014Q4.

```
$ go version
go version go1.4.2 solaris/amd64
```

**Comment by gdamore** [comment]
Yep, you’re going to have to update to 1.5 or better.  The tcell package
simply won’t work with 1.4.x on Solaris/illumos (Sorry).  (It does work
with older versions of Go on other platforms — the problem is that lack of
cgo support on Solaris until 1.5 means we can’t use anything lower.)

**Comment by bahamat** [comment]
In that case I'll close this.
